version: "3"

services: 
    frontend:
        image: frontend
        stdin_open: true
        ports: 
            - "3000:3000"
        networks: 
            - sern-app
    backend:
        image: backend
        ports: 
            - "5001:5001"
        networks: 
            - sern-app
networks: 
    sern-app:
        driver: bridge